name: deeptunnel
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.3=heee7806_1
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - click==8.0.3
    - cycler==0.11.0
    - flask==2.0.2
    - fonttools==4.28.1
    - isodate==0.6.0
    - itsdangerous==2.0.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - kiwisolver==1.3.2
    - markupsafe==2.0.1
    - matplotlib==3.5.0rc1
    - numpy==1.21.4
    - owlready2==0.35
    - packaging==21.2
    - pandas==1.3.4
    - pillow==8.4.0
    - pyparsing==3.0.5
    - python-dateutil==2.8.2
    - pytz==2021.3
    - rdflib==6.0.2
    - scikit-learn==0.24.2
    - scipy==1.7.2
    - setuptools-scm==6.3.2
    - six==1.16.0
    - sortedcontainers==2.4.0
    - threadpoolctl==3.0.0
    - tomli==1.2.2
    - torch==1.10.0
    - typing-extensions==3.10.0.2
    - werkzeug==2.0.2
prefix: /home/demir/anaconda3/envs/deeptunnel
